<a href="https://colab.research.google.com/github/suhyeon03/study_ML_kaggle/blob/main/kaggle_scikit_Learn_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import sklearn
print(sklearn.__version__)

1.6.1


In [3]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [4]:
import pandas as pd
# 붓꽃 데이터 세트를 로딩합니다.
iris = load_iris()
#iris.data는 Iris 데이터 세트에서 피처(feature)만으로 된 데이터를 numopy로 가지고 있습니다.
iris_data = iris.data
#iris.target은 붓꽃 데이터 세트에서 레이블(결정값) 데이터를 numpy로 가지고 있습니다.
iris_label = iris.target
print('iris target값:', iris_label)
print('iris target명:', iris.target_names)

#붓꽃 데이터 세트를 자세히 보기 위해 DataFrame으로 변환합니다.
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)
iris_df['label'] = iris.target
iris_df.head(3)

iris target값: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
iris target명: ['setosa' 'versicolor' 'virginica']


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   

   label  
0      0  
1      0  
2      0

In [5]:
X_train, X_test, y_train, y_test = train_test_split(iris_data, iris_label, test_size=0.2, random_state=11)

In [6]:
# DecisionTreeClassifier 객체 생성
dt_clf = DecisionTreeClassifier(random_state=11)
# 학습 수행
dt_clf.fit(X_train, y_train)

DecisionTreeClassifier(random_state=11)

In [7]:
# 학습이 완료된 DecisionTreeClassifier 객체에서 테스트 데이터 세트로 예측 수행
pred = dt_clf.predict(X_test)

In [8]:
from sklearn.metrics import accuracy_score
print('예측 정확도: {0:4f}'.format(accuracy_score(y_test, pred)))

예측 정확도: 0.933333


In [9]:
# 데이터세트 분리 -> 모델학습 -> 예측수행 -> 평가

#1.사이킷런 기반 프레임워크 익히기

In [10]:
# fit()으로 변환을 위한 사전 구조를 맞춘다 -> transform()로 입력데이터의 차원 변환, 클러스터링, 피쳐 추출등의 실제 작업을 수행한다.

In [11]:
from sklearn.datasets import load_iris
iris_data = load_iris()
print(type(iris_data))


<class 'sklearn.utils._bunch.Bunch'>


In [12]:
# sklearn.utils._bunch.Bunch는 파이썬의 딕셔너리 자료형이랑 비슷하다.
keys = iris_data.keys()
print('붓꽃 데이터 세트의 키들:', keys)

붓꽃 데이터 세트의 키들: dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [13]:
# feature_names, target_name, data, target이 가르키는 값을 출력

In [14]:
print('\n feature_names의 type:', type(iris_data.feature_names))
print('feature_names의 shape:', len(iris_data.feature_names))
print(iris_data.feature_names)

print('\n target_names의 type:', type(iris_data.target_names))
print('target_names의 shape:', len(iris_data.target_names))
print(iris_data.target_names)

print('\n data의 type:', type(iris_data.data))
print('data의 shape:', iris_data.data.shape)
print(iris_data['data'])

print('\n target의 type:', type(iris_data.target))
print('target의 shape:', iris_data.target.shape)
print(iris_data.target)






 feature_names의 type: <class 'list'>
feature_names의 shape: 4
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

 target_names의 type: <class 'numpy.ndarray'>
target_names의 shape: 3
['setosa' 'versicolor' 'virginica']

 data의 type: <class 'numpy.ndarray'>
data의 shape: (150, 4)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 

#2.Model Selection 모듈 소개

##2-1.학습/테스트 데이터 세트 분리 - train_test_split( )

In [15]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

In [16]:
iris = load_iris()
dt_clf = DecisionTreeClassifier()
train_data = iris.data
train_label = iris.target
dt_clf.fit(train_data, train_label)

# 학습 데이터 세트으로 예측 수행
pred = dt_clf.predict(train_data)
print('예측정확도:', accuracy_score(train_label, pred))

# 이미 알고있는 값(학습데이터)으로 훈련했기때문에

예측정확도: 1.0


In [17]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

In [18]:
dt_clf = DecisionTreeClassifier()
iris_data = load_iris()

X_train, X_test, y_train, y_test = train_test_split(iris_data.data, iris_data.target, test_size=0.3, random_state=121)

In [19]:
dt_clf.fit(X_train, y_train)
pred = dt_clf.predict(X_test)
print('예측정확도: {0:.4f}'.format(accuracy_score(y_test, pred)))

예측정확도: 0.9556


##2-2.교차검증


###2-2-1.K-폴드교차검증

In [20]:
# 가장보편적으로 사용되는 교차검증기법이다.
# K개의 데이터 폴드세트를 만들어서 K번만큼 각 폴드세트에 학습과 검증평가를 반복적으로 수행한다.

In [21]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
import numpy as np

In [22]:
iris = load_iris()
features = iris.data
label = iris.target
dt_clf = DecisionTreeClassifier(random_state=156)

# 5개의 폴드 세트로 분리하는 KFold 객체와 폴드 세트별 정확도를 담을 리스트 객체생성
kfold = KFold(n_splits=5)
cv_accuracy = []
print('붓꽃 데이터 세트 크기:', features.shape[0])

붓꽃 데이터 세트 크기: 150


In [23]:
n_iter = 0

# KFold 객체의 split()를 호출하면 폴드별 학습용, 검증용 데이터의 로우 인덱스를 array로 반환
for train_index, test_index in kfold.split(features): #@@중요@@# #피쳐데이터가 사용됨
  # kfold.split()으로 반환된 인덱스를 이용해 학습용, 검증용 테스트 데이터 추출
  X_train, X_test = features[train_index], features[test_index]
  y_train, y_test = label[train_index], label[test_index]
  # 학습 및 예측
  dt_clf.fit(X_train, y_train)
  pred = dt_clf.predict(X_test)
  n_iter += 1
  # 반복 시마다 정확도 측정
  accuracy = np.round(accuracy_score(y_test, pred), 4)
  train_size = X_train.shape[0]
  test_size = X_test.shape[0]
  print('\n# {0} 교차 검증 정확도:{1}, 학습 데이터 크기:{2}, 검증 데이터 크기:{3}'.format(n_iter, accuracy, train_size, test_size))
  print('\n# {0} 검증 세트 인덱스{1}'.format(n_iter,test_index))
  cv_accuracy.append(accuracy)

  # 개별 iteration별 정확도를 합하여 평균 정확도 계산
  print('\n## 평균 검증 정확도', np.mean(cv_accuracy))




# 1 교차 검증 정확도:1.0, 학습 데이터 크기:120, 검증 데이터 크기:30

# 1 검증 세트 인덱스[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

## 평균 검증 정확도 1.0

# 2 교차 검증 정확도:0.9667, 학습 데이터 크기:120, 검증 데이터 크기:30

# 2 검증 세트 인덱스[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]

## 평균 검증 정확도 0.98335

# 3 교차 검증 정확도:0.8667, 학습 데이터 크기:120, 검증 데이터 크기:30

# 3 검증 세트 인덱스[60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89]

## 평균 검증 정확도 0.9444666666666667

# 4 교차 검증 정확도:0.9333, 학습 데이터 크기:120, 검증 데이터 크기:30

# 4 검증 세트 인덱스[ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]

## 평균 검증 정확도 0.941675

# 5 교차 검증 정확도:0.7333, 학습 데이터 크기:120, 검증 데이터 크기:30

# 5 검증 세트 인덱스[120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]

## 평균 검증 정확도 0.9


###2-2-2. Stratified K 폴드


In [24]:
# 불균형한 분포도를 가진 레이블(결정 클래스) 데이터 집합을 위한 K폴드 방식이다.
# 예를 들어 원본 데이터와 유사한 대출사기(거의 정상대출이지만 하나의 대출사기가 특정하나의 학습/테스트 데이터세트에 있으면 안된다.)
# 그러므로 레이블 값의 분포도를 학습/테스트 세트에도 유지하는게 중요하다.

In [25]:
import pandas as pd

iris = load_iris()
iris_df = pd.DataFrame(data=iris.data, columns = iris.feature_names)
iris_df['label'] = iris.target
iris_df['label'].value_counts()

label
0    50
1    50
2    50
Name: count, dtype: int64

In [26]:
kfold = KFold(n_splits=3)
n_iter = 0
for train_index, test_index in kfold.split(iris_df):
  n_iter += 1
  lable_train = iris_df['label'].iloc[train_index]
  label_test = iris_df['label'].iloc[test_index]
  print('## 교차검증: {0}'.format(n_iter))
  print('학습 레이블 데이터분포\n', lable_train.value_counts())
  print('검증 레이블 데이터분포\n', label_test.value_counts())


## 교차검증: 1
학습 레이블 데이터분포
 label
1    50
2    50
Name: count, dtype: int64
검증 레이블 데이터분포
 label
0    50
Name: count, dtype: int64
## 교차검증: 2
학습 레이블 데이터분포
 label
0    50
2    50
Name: count, dtype: int64
검증 레이블 데이터분포
 label
1    50
Name: count, dtype: int64
## 교차검증: 3
학습 레이블 데이터분포
 label
0    50
1    50
Name: count, dtype: int64
검증 레이블 데이터분포
 label
2    50
Name: count, dtype: int64


In [27]:
# kfold 방식과 거의 동일하다.
# 단 하나의 큰 차이는 StratifiedKFold는 데이터 분포도에 따라 학습/검증 데이터를 나누기 때문에
# split()메서드에 인자로 피처 데이터 세트뿐만아니라 레이블 데이터 세트도 반드시 필요하다.

In [28]:
from sklearn.model_selection import StratifiedKFold


In [29]:
from sklearn.model_selection import StratifiedKFold
skf = StratifiedKFold(n_splits=3)
n_iter = 0

for train_index, test_index in skf.split(iris_df, iris_df['label']):
  n_iter += 1
  label_train = iris_df['label'].iloc[train_index]
  label_test = iris_df['label'].iloc[test_index]
  print('## 교차 검증: {0}'.format(n_iter))
  print('학습 레이블 데이터 분포:\n', label_train.value_counts())
  print('검증 레이블 데이터 분포:\n', label_test.value_counts())

## 교차 검증: 1
학습 레이블 데이터 분포:
 label
2    34
0    33
1    33
Name: count, dtype: int64
검증 레이블 데이터 분포:
 label
0    17
1    17
2    16
Name: count, dtype: int64
## 교차 검증: 2
학습 레이블 데이터 분포:
 label
1    34
0    33
2    33
Name: count, dtype: int64
검증 레이블 데이터 분포:
 label
0    17
2    17
1    16
Name: count, dtype: int64
## 교차 검증: 3
학습 레이블 데이터 분포:
 label
0    34
1    33
2    33
Name: count, dtype: int64
검증 레이블 데이터 분포:
 label
1    17
2    17
0    16
Name: count, dtype: int64


In [43]:
dt_clf = DecisionTreeClassifier(random_state=156)

skfold = StratifiedKFold(n_splits=3)
n_iter = 0
cv_accuracy = []

# StratifiedKFold의 호출시 반드시 레이블 데이터 세트도 추가 입력 필여
for train_index, test_index in skfold.split(features, label):
  # split()으로 반환된 인덱스를 이용해 학습용, 검증용 테스트 데이터 추출
  X_train, X_test = features[train_index], features[test_index]
  y_train, y_test = label[train_index], label[test_index]
  # 학습 및 예측
  dt_clf.fit(X_train, y_train)
  pred = dt_clf.predict(X_test)

  # 반복 시마다 정확도 측정
  n_iter += 1
  accuracy = np.round(accuracy_score(y_test, pred), 4)
  train_size = X_train.shape[0]
  test_size = X_test.shape[0]
  print('\n#{0} 교차 검증 정확도:{1}, 학습 데이터 크기:{2}, 검증 데이터 크기:{3}'.format(n_iter, accuracy, train_size, test_size))
  print('\n#{0} 검증 세트 인덱스:{1}'.format(n_iter, test_index))
  cv_accuracy.append(accuracy)

    # 교차 검증별 정확도 및 평균 정확도 계산
  print('\n## 교차 검증별 정확도:', np.round(cv_accuracy, 4))
  print('## 평균 검증 정확도:', np.round(np.mean(cv_accuracy), 4))



#1 교차 검증 정확도:0.98, 학습 데이터 크기:100, 검증 데이터 크기:50

#1 검증 세트 인덱스:[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  50
  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115]

## 교차 검증별 정확도: [0.98]
## 평균 검증 정확도: 0.98

#2 교차 검증 정확도:0.94, 학습 데이터 크기:100, 검증 데이터 크기:50

#2 검증 세트 인덱스:[ 17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82 116 117 118
 119 120 121 122 123 124 125 126 127 128 129 130 131 132]

## 교차 검증별 정확도: [0.98 0.94]
## 평균 검증 정확도: 0.96

#3 교차 검증 정확도:0.98, 학습 데이터 크기:100, 검증 데이터 크기:50

#3 검증 세트 인덱스:[ 34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  83  84
  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149]

## 교차 검증별 정확도: [0.98 0.94 0.98]
## 평균 검증 정확도: 0.9667


In [ ]:
# 일반적인 분류는 k폴드가 아니라 stratified k 폴드로 분할돼야 한다. 단 회귀에서는 사용불가능하다. -> 회귀는 연속된 숫자이기에 결정값 별로 분포가 의미가 없다.

###2-2-3.교차검증을 보다 간편하게 - cross_val_score()

In [ ]:
# cross_val_score(estimater, X, y=None, scoring=None, cv=None, n_jobs=1, verbose=0, fit_params=None, pre_dispatch='2*n_jobs')
  # 이중에서 estimater, X, y, scoring, cv가 주요 파라미터이다.
  # estimater은 분류/회귀 알고리즘 클래스를 말한다.
  # X는 피처데이터세트, y는 레이블 데이터 세트, scoring은 예측 성능 평가지표를 기술한다.
  # cross_val_score() 수행 후 반환 값은 scoring 파라미터로 지정된 성능 지표 측정값을 배열 형태로 반환한다.

In [44]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score, cross_validate
from sklearn.datasets import load_iris

iris_data = load_iris()
dt_clf = DecisionTreeClassifier(random_state=156)

data = iris_data.data
label = iris_data.target

# 성능 지표는 정확도(accuaracy), 교차 검증 세트는 3개
scores = cross_val_score(dt_clf,data,label,scoring='accuracy', cv=3) # cv의 지정횟수만큼 평가 결과값을 배열로 반환한다.
print('교차 검증별 정확도:', np.round(scores, 4))
print('평균 검증 정확도:', np.round(np.mean(scores), 4))

교차 검증별 정확도: [0.98 0.94 0.98]
평균 검증 정확도: 0.9667


In [41]:
# cross_validate()는 여러개의 평가지표를 반환하고, 성능 평가 지표와 수행시간도 제공된다.

array([<module 'numpy' from '/usr/local/lib/python3.11/dist-packages/numpy/__init__.py'>,
       <module 'numpy' from '/usr/local/lib/python3.11/dist-packages/numpy/__init__.py'>,
       <module 'numpy' from '/usr/local/lib/python3.11/dist-packages/numpy/__init__.py'>],
      dtype=object)

###2-2-4.GridSearchCV_교차 검증과 최적 하이퍼 파라미터 튜닝을 한번에

In [49]:
grid_parameters = {'max_depth':[1,2,3],
                   'min_samples_split':[2,3]
                   }

In [50]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV

# 데이터를 로딩하고 학습 데이터와 테스트 데이터 분리
iris = load_iris()
X_train, X_test, y_train, y_test = train_test_split(iris_data.data, iris_data.target, test_size=0.2, random_state=121)
dtree = DecisionTreeClassifier()

### 파라미터를 딕셔너리 형태로 설정
## 테스트할 하이퍼 파라미터 세트는 딕셔너리 형태로 하이퍼 파라미터의 명칭은 문자열 Key값으로, 하이퍼 파라미터의 값은 리스트 형으로 설정한다.
parameters = {'max_depth':[1,2,3], 'min_samples_split':[2,3]}

In [51]:
import pandas as pd

# param_grid의 하이퍼파라미터를 3개의 train , test set fold로 나누어 테스트 수행 설정.
### refit =True가 defaul임. True이면 가장 좋은 파라미터 설정으로 재학습시킴.
### param_grid의 결과를 cv_result_ 속성에 기록하고 딕셔너리 형태로 키와 리스트형태의 value를 가진다.
grid_dtree = GridSearchCV(dtree, param_grid=parameters, cv=3, refit=True)

# 붗꽃 학습 데이터로 param_grid의 하이퍼 파라미터를 순차적으로 학습/평가
grid_dtree.fit(X_train, y_train)

# GridSearchCV 결과를 추출해 DataFrame으로 변환
scores_df = pd.DataFrame(grid_dtree.cv_results_)
scores_df[['params', 'mean_test_score', 'rank_test_score', 'split0_test_score', 'split1_test_score', 'split2_test_score']]

# params는 칼럼에는 수행할 때마다 적용된 개별 하이퍼 파라미터값을 나타낸다.
# rank_test_score는 하이퍼 파라미터별로 성능이 좋은 score 순위를 나타낸다.
# mean_test_score는 개별 하이퍼 파라미터별로 cv의 폴딩 데이터세트에 대해 총 수행한 평가 평균이다.


params  mean_test_score  rank_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}         0.700000                5   
1  {'max_depth': 1, 'min_samples_split': 3}         0.700000                5   
2  {'max_depth': 2, 'min_samples_split': 2}         0.958333                3   
3  {'max_depth': 2, 'min_samples_split': 3}         0.958333                3   
4  {'max_depth': 3, 'min_samples_split': 2}         0.975000                1   
5  {'max_depth': 3, 'min_samples_split': 3}         0.975000                1   

   split0_test_score  split1_test_score  split2_test_score  
0              0.700                0.7               0.70  
1              0.700                0.7               0.70  
2              0.925                1.0               0.95  
3              0.925                1.0               0.95  
4              0.975                1.0               0.95  
5              0.975                1.0               0.95

In [ ]:
# 그리고 이때 결과 값은 best_params, best_score_ 속성에 기록된다.

In [52]:
print('GridSearchCV 최적 파라미터:', grid_dtree.best_params_)
print('GridSearchCV 최고 정확도:{0:.4f}'.format(grid_dtree.best_score_))

GridSearchCV 최적 파라미터: {'max_depth': 3, 'min_samples_split': 2}
GridSearchCV 최고 정확도:0.9750


In [55]:
# GridSearchCV의 refit으로 이미 학습된 estimater 반환
estimater = grid_dtree.best_estimator_

# GridSearchCV의 best_estimater_는 이미 최적 학습이 됐으므로 별도 학습이 필요 없음
pred = estimater.predict(X_test)
print('테스트 데이터 세트 정확도:{0:4f}'.format(accuracy_score(y_test, pred)))

테스트 데이터 세트 정확도:0.966667


In [ ]:
# 일반적으로 학습데이터를 GridSearchCV를 이용해 최적 하이퍼 파라미터 튜닝을 수행한 뒤 별도의 테스트 세트에서 이를 푱가하는 것이 일반적인 머신러닝 모델 적용방법이다.